volumes:
  pg_data:
  root-folder:


services:
  postgres:
    image: postgres:17
    container_name: n8n-postgres
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      proxy:


  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    user: "0:0"
    security_opt:
      - no-new-privileges:true

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=https"
      - "traefik.http.routers.n8n.rule=Host(`automation.${DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n.middlewares=AddForwardedHeader@file"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.routers.n8n.service=n8n"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=proxy"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_HOST=automation.${DOMAIN_NAME}
      - N8N_PROTOCOL=https
      - N8N_PROXY_HOPS=1
      - WEBHOOK_URL=https://automation.${DOMAIN_NAME}
      - GENERIC_TIMEZONE=Etc/UTC
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - root-folder:/root/.n8n
    networks:
      proxy:


networks:
  proxy:
    external: true
