services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.entrypoints=https"
      - "traefik.http.routers.it-tools.rule=Host(`tools.${DOMAIN_NAME}`)"
      - "traefik.http.routers.it-tools.tls.certresolver=myresolver"
      - "traefik.http.routers.it-tools.service=it-tools"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    restart: unless-stopped
    container_name: it-tools
    networks:
      proxy:


networks:
  proxy:
    external: true
