server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_HOST}:3100/loki/api/v1/push

scrape_configs:
  - job_name: backup-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backup-manager
          hostname: ${HOSTNAME}
          source: cron
          __path__: /var/log/backup-*.log
