services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    container_name: uptime-kuma
    volumes:
      - data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.${DOMAIN_NAME}`)"
      - "traefik.http.routers.uptime-kuma.middlewares=AddForwardedHeader@file"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=myresolver"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    networks:
      proxy:


networks:
  proxy:
    external: true

volumes:
  data: {}
