services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - grocy_config:/config
    ports:
      - 9283:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grocy.entrypoints=https"
      - "traefik.http.routers.grocy.rule=Host(`grocy.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grocy.tls.certresolver=myresolver"
      - "traefik.http.routers.grocy.service=grocy"
      - "traefik.http.services.grocy.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      proxy:


networks:
  proxy:
    external: true

volumes:
  grocy_config:
