version: '3'

x-shared:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - chatwoot-storage_data:/app/storage
    networks:
      proxy:


services:

  rails:
    <<: *base
    container_name: chatwoot-rails
    depends_on:
      - chatwoot-postgres
      - chatwoot-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatwoot.entrypoints=https"
      - "traefik.http.routers.chatwoot.rule=Host(`chatwoot.${DOMAIN_NAME}`)"
      - "traefik.http.routers.chatwoot.middlewares=AddForwardedHeader@file"
      - "traefik.http.routers.chatwoot.tls=true"
      - "traefik.http.routers.chatwoot.tls.certresolver=myresolver"
      - "traefik.http.routers.chatwoot.service=chatwoot"
      - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: [ 'bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]
    restart: always

  sidekiq:
    <<: *base
    container_name: chatwoot-sidekiq
    depends_on:
      - chatwoot-postgres
      - chatwoot-redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: [ 'bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml' ]
    restart: always

  chatwoot-postgres:
    container_name: chatwoot-postgres
    image: pgvector/pgvector:pg16
    restart: always
    networks:
      proxy:
    volumes:
      - chatwoot-postgres_data:/var/lib/postgresql/data
    env_file: .env

  chatwoot-redis:
    container_name: chatwoot-redis
    image: redis:alpine
    restart: always
    command: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]
    env_file: .env
    volumes:
      - chatwoot-redis_data:/data
    networks:
      proxy:


volumes:
  chatwoot-storage_data:
  chatwoot-postgres_data:
  chatwoot-redis_data:


networks:
  proxy:
    external: true
