- name: Deploy backup scripts .env
  template:
    src: "{{ playbook_dir }}/../templates/backup-env.j2"
    dest: "{{ scripts_env_path }}"
    mode: '0600'
    owner: root
  tags: vault

- name: Deploy komodo .env
  template:
    src: "{{ playbook_dir }}/../templates/komodo-env.j2"
    dest: "{{ komodo_env_path }}"
    mode: '0600'
    owner: root
  tags: vault

- name: Deploy infisical service .env
  template:
    src: "{{ playbook_dir }}/../templates/infisical-env.j2"
    dest: "{{ infisical_env_path }}"
    mode: '0600'
    owner: root
  when: inventory_hostname == 'local'
  tags: vault

- name: Deploy traefik service .env
  template:
    src: "{{ playbook_dir }}/../templates/traefik-env.j2"
    dest: "{{ traefik_env_path }}"
    mode: '0600'
    owner: root
  when: inventory_hostname == 'local'
  tags: vault
